task: inference

fast_inference:  # onnx, trt, deploy or Empty
data:
  source: /home/lucas/VSCodeProjects/YOLO/data/dev/images/val/
  image_size: ${image_size}
  data_augment: {}
nms:
  min_confidence: 0.5
  min_iou: 0.5
  max_bbox: 500
save_predict: True
